---
- package:
    name: apt-transport-https
    state: installed

- name: Install Package Cloud GPG key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add APT repository
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/stable/debian/ jessie main'
    state: present

- name: Install packages
  apt:
    name: "{{ grafana_packages }}"
    state: present
  notify:
    - restart grafana
