---
- name: Install apt-transport-https
  package:
    name: apt-transport-https
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Package Cloud GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add APT repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: Install
  apt:
    name: "grafana={{ openio_grafana_version }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  ignore_errors: "{{ ansible_check_mode }}"
...
