---
- name: Include per distro vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Include per distro tasks
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure directories
  file:
    path: "{{ item }}"
    owner: grafana
    group: grafana
    mode: 0644
    state: directory
  with_items:
    "{{ grafana_paths.values() }}"

- name: Configure
  template:
    src: "grafana.ini.j2"
    dest: "{{ grafana_paths['conf'] | realpath }}/grafana.ini"
    owner: grafana
    group: grafana
    mode: 0644

- name: Overwrite systemd unit
  template:
    src: "grafana-server.service.j2"
    dest: "/usr/lib/systemd/system/grafana-server.service"
    owner: root
    group: root
    mode: 0644

- name: Reload daemon
  systemd: daemon_reload=yes
  when: ansible_virtualization_type != 'docker'

- name: Provision - datasources
  template:
    src: "prometheus.yaml.j2"
    dest: "{{ grafana_paths['datasources'] | realpath }}/prometheus.yaml"
    owner: grafana
    group: grafana
    mode: 0644

- name: Provision - dashboards
  copy:
    src: "{{item}}.json"
    dest: "{{ grafana_paths['dashboards'] | realpath }}/{{ item }}.json"
    owner: grafana
    group: grafana
    mode: 0644
    backup: true
  with_items: "{{ grafana_dashboards + (['filesystem_connector'] if grafana_oiofs_enabled else []) }}"

- name: Provision - dashboard config
  template:
    src: "openio.yml.j2"
    dest: "{{ grafana_paths['dashboards'] | realpath }}/openio.yml"
    owner: grafana
    group: grafana
    mode: 0644

- name: Start service
  service:
    name: "{{ grafana_service_name }}"
    state: "{{'started' if grafana_provision_only else 'restarted' }}"
    enabled: true

- name: Ensure the service is started
  wait_for:
    host: "{{ grafana_bind_address }}"
    port: "{{ grafana_http['port'] }}"
    delay: 10

- name: Set overview as the default dashboard
  debug:
    msg: "{{ grafana_http | set_default_dashboard(grafana_auth, grafana_bind_address) }}"
  when:
    - not grafana_provision_only
...
