---
- name: Install
  package:
    name: "grafana"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  ignore_errors: "{{ ansible_check_mode }}"
  tags: install
...
