---
- name: "Configure repository for {{ ansible_distribution}} {{ ansible_distribution_major_version }}"
  yum_repository:
    name: grafana
    description: "Grafana packages for Entreprise Linux $releasever - $basearch"
    file: grafana
    baseurl: "https://packages.grafana.com/oss/rpm"
    enabled: true
    gpgkey: https://packages.grafana.com/gpg.key
    gpgcheck: true
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Install
  package:
    name: "grafana-{{ openio_grafana_version }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  ignore_errors: "{{ ansible_check_mode }}"
...
